"""empty message

Revision ID: 175e6778271a
Revises: b7f6513bf3eb
Create Date: 2020-03-25 15:39:48.522891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175e6778271a'
down_revision = 'b7f6513bf3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Objective', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('Objective', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Objective', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Objective', 'description')
    # ### end Alembic commands ###
